In [1]:
import subprocess
import pandas as pd
import numpy as np
import csv


In [2]:
def matGen(n, m, m2):

    LONG_LONG_MAX =  9223372036854775807

    #change values here!
    # n = 50
    # m = 50
    # m2 = 50

    #f =  open("Matrix_out.txt")
    mat = np.random.randint(0,1000,size=(n,m))
    print(mat)
    np.savetxt("matrix1.txt",mat,fmt='%i')

    mat2 = np.random.randint(0,1000,size=(m,m2))
    print(mat2)
    np.savetxt("matrix2.txt",mat2,fmt='%i')

    matRes = np.matmul(mat,mat2)
    print(matRes)
    print(matRes.shape)
    np.savetxt("matrixres.txt",matRes,fmt='%i')

In [3]:
subprocess.call(["gcc", "P1.c", "-o","P1.out", "-pthread"])
subprocess.call(["gcc", "P2.c", "-o","P2.out", "-pthread"])
subprocess.call(["gcc", "schedulercopy.c", "-o","sched.out"])


# subprocess.call("gcc schedulercopy.c")

f1 = open('datasched.csv', 'w')

writer1 = csv.writer(f1)

header1 = ['dim1', 'dim2', 'dim3', 'TAT(ns)', 'wait(ns)', 'switching_ovhd(ns)']

writer1.writerow(header1)

f1.close()

In [7]:
i = j = k = 1500
matGen(i, j, k)

[[858 265 559 ... 735 217 342]
 [624 616 471 ... 446  85 427]
 [ 38 655 441 ... 912  46 435]
 ...
 [433 647 761 ... 138 292 946]
 [537 949 750 ... 222 734 524]
 [249 337 246 ... 198 260 295]]
[[372 558 304 ... 676  20 414]
 [318 888 389 ... 246 764 870]
 [984 231 225 ... 988 284 680]
 ...
 [585 223 268 ... 986 513 908]
 [201 573 625 ... 116 981 147]
 [300 508 807 ...  83 741 914]]
[[373319387 378777449 378940534 ... 375513000 379424478 388604066]
 [383805928 386110201 388941247 ... 381584027 383311411 394555247]
 [378100918 384068751 377046568 ... 369677066 368910721 388651211]
 ...
 [375164850 379831595 383220731 ... 370322143 372957630 392888362]
 [383645309 390539934 386374757 ... 380801750 382009370 398684963]
 [375477257 383120696 376966515 ... 368942140 367942351 393684603]]
(1500, 1500)


In [8]:

execstring = "./sched.out " + str(i) + " " + str(j) + " " + str(k) + " matrix1.txt matrix2.txt out.txt"
tmp = subprocess.call(execstring.split())

Stopped P1
Stopped P2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Start 2
Stop 2
Start 1
Stop 1
Sta

In [ ]:
for i in range(1, 1000, 10):
    for j in range(1, 1000, 10):
        for k in range(1, 1000, 10):
            matGen(i, j, k)
            execstring = "./sched.out " + str(i) + " " + str(j) + " " + str(k) + " matrix1.txt matrix2.txt out.txt 8 8"
            tmp = subprocess.call(execstring.split())


In [ ]:
# for i in range(1, 50):
#     for j in range(1,6):
#         p1 = "./P1.out "+str(n)+" "+str(m)+" "+str(m2)+" "+"matrix1.txt matrix2.txt out.txt "+ str(i) +" 1"
#         tmp=subprocess.call(p1.split()) 
#         print("printing result")
#         #print(tmp)
#         p2 = "./P2.out "+str(n)+" "+str(m)+" "+str(m2)+" "+"matrix1.txt matrix2.txt out.txt 1 "+ str(i)
#         tmp=subprocess.call(p2.split()) 
#         print("printing result")
#         #print(tmp)

# # #dataP1.txt

In [ ]:
df = pd.read_csv("datasched.csv")

# df = df.groupby('num_threads').mean('time(ns)')
print(df.head)